import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export type MonthExport = {
  title: string;
  salary: number;
  income: number;
  expenses: number;
  balance: number;
  breakdown: { name: string; expense: number; income: number }[];
  items: {
    description: string;
    category?: string;
    type: string;
    amount: number;
    created_at: string;
  }[];
  accent: string;
  fmt: (n: number) => string;
};

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function buildMonthHtml(d: MonthExport): string {
  const positive = d.balance >= 0;
  const breakdownRows = d.breakdown
    .map((c) => {
      const exp = c.expense > 0 ? `−${d.fmt(c.expense)}` : "";
      const inc = c.income > 0 ? `+${d.fmt(c.income)}` : "";
      return `<tr>
        <td class="cat-name">${esc(c.name)}</td>
        <td class="amt income">${inc}</td>
        <td class="amt expense">${exp}</td>
      </tr>`;
    })
    .join("");

  const itemRows = d.items
    .map((t) => {
      const day = new Date(t.created_at).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
      });
      const isExpense = t.type === "expense";
      return `<tr>
        <td class="date">${day}</td>
        <td>${esc(t.description)}</td>
        <td class="cat-name">${esc(t.category || "Other")}</td>
        <td class="amt ${isExpense ? "expense" : "income"}">${isExpense ? "−" : "+"}${d.fmt(t.amount)}</td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #121212; padding: 48px 44px; background: #ffffff; }
  .brand { font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: ${d.accent}; margin-bottom: 8px; }
  h1 { font-family: Georgia, 'Times New Roman', serif; font-weight: 500; font-size: 34px; margin-bottom: 28px; }
  .stats { display: flex; border: 0.5px solid #e4e4e4; border-radius: 14px; overflow: hidden; margin-bottom: 32px; }
  .stat { flex: 1; padding: 18px 14px; text-align: center; border-right: 0.5px solid #e4e4e4; }
  .stat:last-child { border-right: none; }
  .stat .label { font-size: 10px; letter-spacing: 1.5px; text-transform: uppercase; color: #8a8a8a; margin-bottom: 6px; }
  .stat .value { font-family: Georgia, serif; font-size: 20px; }
  .stat.balance { background: ${d.accent}; }
  .stat.balance .label { color: rgba(255,255,255,0.75); }
  .stat.balance .value { color: #ffffff; }
  .income { color: #0F3D2E; }
  .expense { color: #C0453B; }
  ${positive ? "" : ".stat.balance { background: #C0453B; }"}
  h2 { font-family: Georgia, serif; font-weight: 500; font-size: 20px; margin: 28px 0 12px; }
  table { width: 100%; border-collapse: collapse; }
  th { font-size: 10px; letter-spacing: 1.5px; text-transform: uppercase; color: #8a8a8a; text-align: left; padding: 8px 10px; border-bottom: 0.5px solid #e4e4e4; font-weight: 500; }
  td { padding: 10px; font-size: 13px; border-bottom: 0.5px solid #f0f0f0; }
  td.amt, th.amt { text-align: right; font-family: Georgia, serif; font-size: 14px; }
  td.date { color: #8a8a8a; white-space: nowrap; width: 70px; }
  td.cat-name { color: #3a3a3a; }
  .footer { margin-top: 40px; font-size: 10px; letter-spacing: 2px; text-transform: uppercase; color: #b5b5b5; text-align: center; }
</style>
</head>
<body>
  <div class="brand">Salary Manager</div>
  <h1>${esc(d.title)}</h1>

  <div class="stats">
    <div class="stat"><div class="label">Salary</div><div class="value">${d.fmt(d.salary)}</div></div>
    <div class="stat"><div class="label">Extra Income</div><div class="value income">+${d.fmt(d.income)}</div></div>
    <div class="stat"><div class="label">Expenses</div><div class="value expense">−${d.fmt(d.expenses)}</div></div>
    <div class="stat balance"><div class="label">Balance</div><div class="value">${d.fmt(d.balance)}</div></div>
  </div>

  ${d.breakdown.length ? `
  <h2>Category Breakdown</h2>
  <table>
    <tr><th>Category</th><th class="amt">Income</th><th class="amt">Expenses</th></tr>
    ${breakdownRows}
  </table>` : ""}

  ${d.items.length ? `
  <h2>Transactions</h2>
  <table>
    <tr><th>Date</th><th>Description</th><th>Category</th><th class="amt">Amount</th></tr>
    ${itemRows}
  </table>` : ""}

  <div class="footer">Generated by Salary Manager</div>
</body>
</html>`;
}

export async function shareMonthPdf(d: MonthExport): Promise<void> {
  const html = buildMonthHtml(d);
  if (Platform.OS === "web") {
    // Opens the browser print dialog where the user can save as PDF.
    await Print.printAsync({ html });
    return;
  }
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: `${d.title} Summary`,
      UTI: "com.adobe.pdf",
    });
  }
}
