import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export type YearRow = {
  label: string; // "January"
  has: boolean;
  salary: number;
  income: number;
  expenses: number;
  saved: number;
};

export type YearExport = {
  year: number;
  rows: YearRow[];
  totalIncome: number;
  totalExpenses: number;
  totalSaved: number;
  accent: string;
  fmt: (n: number) => string;
};

export function buildYearHtml(d: YearExport): string {
  const rows = d.rows
    .map((r) => {
      if (!r.has) {
        return `<tr class="muted"><td>${r.label}</td><td class="amt">—</td><td class="amt">—</td><td class="amt">—</td><td class="amt">—</td></tr>`;
      }
      return `<tr>
        <td>${r.label}</td>
        <td class="amt">${d.fmt(r.salary)}</td>
        <td class="amt income">+${d.fmt(r.income)}</td>
        <td class="amt expense">−${d.fmt(r.expenses)}</td>
        <td class="amt ${r.saved >= 0 ? "income" : "expense"}">${d.fmt(r.saved)}</td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #121212; padding: 48px 44px; background: #ffffff; }
  .brand { font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: ${d.accent}; margin-bottom: 8px; }
  h1 { font-family: Georgia, 'Times New Roman', serif; font-weight: 500; font-size: 34px; margin-bottom: 28px; }
  .stats { display: flex; border: 0.5px solid #e4e4e4; border-radius: 14px; overflow: hidden; margin-bottom: 32px; }
  .stat { flex: 1; padding: 18px 14px; text-align: center; border-right: 0.5px solid #e4e4e4; }
  .stat:last-child { border-right: none; }
  .stat .label { font-size: 10px; letter-spacing: 1.5px; text-transform: uppercase; color: #8a8a8a; margin-bottom: 6px; }
  .stat .value { font-family: Georgia, serif; font-size: 20px; }
  .stat.saved { background: ${d.accent}; }
  .stat.saved .label { color: rgba(255,255,255,0.75); }
  .stat.saved .value { color: #ffffff; }
  .income { color: #0F3D2E; }
  .expense { color: #C0453B; }
  table { width: 100%; border-collapse: collapse; }
  th { font-size: 10px; letter-spacing: 1.5px; text-transform: uppercase; color: #8a8a8a; text-align: left; padding: 8px 10px; border-bottom: 0.5px solid #e4e4e4; font-weight: 500; }
  td { padding: 10px; font-size: 13px; border-bottom: 0.5px solid #f0f0f0; }
  td.amt, th.amt { text-align: right; font-family: Georgia, serif; font-size: 14px; }
  tr.muted td { color: #c4c4c4; }
  .footer { margin-top: 40px; font-size: 10px; letter-spacing: 2px; text-transform: uppercase; color: #b5b5b5; text-align: center; }
</style>
</head>
<body>
  <div class="brand">Salary Manager</div>
  <h1>${d.year} — Year Overview</h1>

  <div class="stats">
    <div class="stat"><div class="label">Extra Income</div><div class="value income">+${d.fmt(d.totalIncome)}</div></div>
    <div class="stat"><div class="label">Expenses</div><div class="value expense">−${d.fmt(d.totalExpenses)}</div></div>
    <div class="stat saved"><div class="label">Saved</div><div class="value">${d.fmt(d.totalSaved)}</div></div>
  </div>

  <table>
    <tr><th>Month</th><th class="amt">Salary</th><th class="amt">Income</th><th class="amt">Expenses</th><th class="amt">Saved</th></tr>
    ${rows}
  </table>

  <div class="footer">Generated by Salary Manager</div>
</body>
</html>`;
}

export async function shareYearPdf(d: YearExport): Promise<void> {
  const html = buildYearHtml(d);
  if (Platform.OS === "web") {
    await Print.printAsync({ html });
    return;
  }
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: `${d.year} Year Overview`,
      UTI: "com.adobe.pdf",
    });
  }
}
